DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS reference CASCADE;
DROP TABLE IF EXISTS book CASCADE;
DROP TABLE IF EXISTS article CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS misc CASCADE;
